i = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(i))
print('É alfanumérico? ', i.isalnum())
print('É alfabético? ', i.isalpha())
print('É numérico? ', i.isnumeric())
print('Está em letras maiúsculas? ', i.isupper())
print('Está em letras minúsculas? ', i.islower())
print('É somente espaços? ', i.isspace())